[opener]
edit = [
    { run = 'nvim "$@"', block = true } 
]
video = [
    { run = 'vlc "$@"', desc = "VLC", orphan = true }
]
audio = [
    { run = 'mpv "$@" mpv --force-window', desc = "MPV", orphan = true }
]
images = [
    { run = 'sxiv "$@"', desc = "SXIV", orphan = true }
]

nautilus = [
    { run = 'nautilus "$@"', desc = "in file manager", orphan = true }
]


[open]
rules = [
  # { mime = "*/", use = [ "edit", "open", "reveal", "nautilus" ] },

  { mime = "video/*", use = [ "video", "open", "reveal", "nautilus" ] },
  { mime = "audio/*", use = [ "audio", "open", "reveal", "nautilus" ] },
  { mime = "image/*", use = [ "images", "open", "reveal", "nautilus" ] },
  { mime = "text/*",  use = [ "edit", "open", "reveal", "nautilus" ] },

  { mime = "application/json", use = [ "edit", "reveal" ] },
  { mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "*", use = [ "open", "edit", "reveal", "nautilus" ] },
]

# keymap.toml

